name: intern_assignment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  just_audio: ^0.10.5
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  record: ^6.1.2
  url_launcher: ^6.3.0
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
